AWSTemplateFormatVersion: "2010-09-09"
Description: Provisioning a platform stack

Parameters:
  WebsiteDNS:
    Type: String
    Description: Website having a DNS with WWW
    AllowedPattern: ".+"
    ConstraintDescription: This field cannot be empty

  HostedZoneId:
    Type: String
    Description: Website DNS Hosted Zone Id
    AllowedPattern: ".+"
    ConstraintDescription: This field cannot be empty

Resources:
  S3BucketWithWWW:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub "www.${WebsiteDNS}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags:
        - Key: Website
          Value: !Ref WebsiteDNS

  S3BucketWithWWWBucketPolicy:
    DependsOn: 
      - S3BucketWithWWW
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: WebsiteDNSPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3BucketWithWWW
                - /*
      Bucket: !Ref S3BucketWithWWW

  WebsiteSSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref WebsiteDNS
      DomainValidationOptions: 
        - DomainName: !Ref WebsiteDNS
          HostedZoneId: !Ref HostedZoneId
      SubjectAlternativeNames: 
        - !Sub "*.${WebsiteDNS}"
      ValidationMethod: DNS

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Unique Domain Hosting Environment

  WebsiteCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn: 
      - S3BucketWithWWW
      - CloudFrontOriginAccessIdentity
      - WebsiteSSLCertificate
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_All
        Aliases:
          - !Sub ${WebsiteDNS}
        Origins:
          - DomainName: !Sub ${S3BucketWithWWW}.s3.${AWS::Region}.amazonaws.com
            Id: !Sub ${S3BucketWithWWW}.s3.${AWS::Region}.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        Enabled: True
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/index.html'
        DefaultCacheBehavior: 
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 #Caching Policy Managed By AWS
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: True
          # ForwardedValues:
            # QueryString: True
          DefaultTTL: 3600 # in seconds
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: !Sub ${S3BucketWithWWW}.s3.${AWS::Region}.amazonaws.com
        ViewerCertificate: 
          # AcmCertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${WebsiteSSLCertificate}
          AcmCertificateArn: !Ref WebsiteSSLCertificate
          MinimumProtocolVersion: TLSv1.2_2021 
          SslSupportMethod: sni-only
        HttpVersion: http2
        IPV6Enabled: true
        DefaultRootObject: index.html

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - WebsiteCloudfront
    Properties:
      Name: !Sub ${WebsiteDNS}
      HostedZoneId: !Sub ${HostedZoneId}
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteCloudfront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  S3BucketWithWWW:
    Value: !Sub ${S3BucketWithWWW}
  WebsiteUrlWWW:
    Value: !GetAtt 
          - S3BucketWithWWW
          - WebsiteURL
  SSLCertificate: 
    Value: !Ref WebsiteSSLCertificate
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3BucketWithWWW